name: demotranslate
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.10
 - pip
 - pip:
   - streamlit==1.25.*
   - azure-storage-blob==12.7.*
   - azure-identity==1.3.*
   - pyperclip==1.8.*
