name: Trigger auto deployment for demotranslate

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/demotranslate-AutoDeployTrigger-f442c3e0-083f-4b4b-8c4d-084796996773.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: heinousacr.azurecr.io
          username: ${{ secrets.DEMOTRANSLATE_REGISTRY_USERNAME }}
          password: ${{ secrets.DEMOTRANSLATE_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: heinousacr.azurecr.io/demotranslate:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOTRANSLATE_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n demotranslate -g zf-demo-translate --server heinousacr.azurecr.io --username  ${{ secrets.DEMOTRANSLATE_REGISTRY_USERNAME }} --password ${{ secrets.DEMOTRANSLATE_REGISTRY_PASSWORD }}
            az containerapp update -n demotranslate -g zf-demo-translate --image heinousacr.azurecr.io/demotranslate:${{ github.sha }}
